### ISSUE TITLE
Submitting search adds more results to the existing ones

### ISSUE THREAD

**Issue by arrested-developer** [FACxBeamery/gifApp-TomLyndsey#8]
If I search for a new term, I can't see my results at first, but when I look down the page they've been appended to the ones already there.

When a new search term is entered, clear the existing gifs before adding the new ones.

**Comment by arrested-developer** [comment]
Are you closing this because you've already addressed it?

**Comment by thomas-galligan** [comment]
yes! We actually fixed it last night but hadn't merged the changes to master.

**Comment by arrested-developer** [comment]
🙌🏻
