### ISSUE TITLE
Make your code more modular

### ISSUE THREAD

**Issue by arrested-developer** [FACxBeamery/gifApp-TomLyndsey#9]
https://github.com/FACxBeamery/gifApp-TomLyndsey/blob/ae60eaac59c334a10c99d5f932745361f9a69b5e/main.js#L19-L29

This section of code does a lot of different things:

- loop through the results
- for each result, get the URL of the image
- create a new `img` element and add it to the page

Separate this code out into one or more pure functions, and name your functions and their parameters well to help with readability.

**Comment by thomas-galligan** [comment]
We've added a new function addGIF(url) that adds a gif to the page when supplied with its url. This function is now called in the for loop to aid readability.
